version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: farol-da-fe-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      # - GEMINI_API_KEY=${GEMINI_API_KEY} # A chave da IA deve ser injetada localmente
    restart: unless-stopped
